flowchart TD
    event_qocqkdgjjeipnqs0zy71["'Stop, stop, stop': Listen to LaGuardia control to..."]
    event_zt0wzhxgkmutoy3ydbrm["How the deadly LaGuardia Airport crash unfolded | ..."]
    event_j315yakicq010bb535om["Iran war shows norms of international conflicts ha..."]
    event_l0ptzb1l6wccwhl43b1c["Everyday life in Asia is being upended by Iran war..."]
    event_bv7lem9v1mex2dstnu5o["Pilots killed in LaGuardia plane crash named | Inv..."]
    event_dfbgf9r22o1ligugnr21["Ultimatums, diplomacy and a trip to Graceland as T..."]
    event_rh8v478lpi62nseecbac["What Iranians make of the possibility of talks to ..."]
    event_nca2efl1tyabmkcjahcn["A committed pharmacist and a homesick blogger – th..."]
    event_n7lmqwcztq8w749q7c8p["What happened in the seconds before Air Canada pla..."]
    event_5dy15t74yqrisclcpwqw["Oil falls and shares rebound after Trump says talk..."]
    event_6bryikbosq7qoo1dake1["US' and Iran's options for ending war narrow the l..."]
    event_4295w1iqvq46myqatda5["Could Iranian missiles reach London and Paris? | S..."]
    event_qocqkdgjjeipnqs0zy71 -->|1.0| event_zt0wzhxgkmutoy3ydbrm
    event_j315yakicq010bb535om -->|0.95| event_l0ptzb1l6wccwhl43b1c
    event_zt0wzhxgkmutoy3ydbrm -->|0.95| event_bv7lem9v1mex2dstnu5o
    event_dfbgf9r22o1ligugnr21 -->|0.95| event_rh8v478lpi62nseecbac
    event_nca2efl1tyabmkcjahcn -->|0.9| event_l0ptzb1l6wccwhl43b1c
    event_nca2efl1tyabmkcjahcn -->|0.9| event_dfbgf9r22o1ligugnr21
    event_zt0wzhxgkmutoy3ydbrm -->|0.9| event_n7lmqwcztq8w749q7c8p
    event_5dy15t74yqrisclcpwqw -->|0.9| event_rh8v478lpi62nseecbac
    event_6bryikbosq7qoo1dake1 -->|0.9| event_dfbgf9r22o1ligugnr21
    event_6bryikbosq7qoo1dake1 -->|0.9| event_nca2efl1tyabmkcjahcn
    event_6bryikbosq7qoo1dake1 -->|0.9| event_4295w1iqvq46myqatda5
    event_dfbgf9r22o1ligugnr21 -->|0.9| event_l0ptzb1l6wccwhl43b1c